apiVersion: v1
kind: ConfigMap
metadata:
  name: oc-collector-conf
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.opencensus.name }}
    component: {{ .Values.opencensus.component }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
data:
  oc-collector-config: |
    receivers:
      opencensus:
        port: 55678
      zipkin:
        port: 9411
    queued-exporters:
      jaeger-all-in-one:
        num-workers: 4
        queue-size: 100
        retry-on-failure: true
        sender-type: jaeger-thrift-http
        jaeger-thrift-http:
          collector-endpoint: http://jaeger.tracing:14268/api/traces
          timeout: 5s
